[project]
name = "avhelper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.16.4",
    "sqlmodel>=0.0.24",
    "strawberry-graphql>=0.278.0",
]
