"""initial_migration

Revision ID: 3e655349cef0
Revises: 
Create Date: 2025-07-28 14:58:19.211248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e655349cef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nyaa_post')
    op.drop_table('nyaa_post_trends')
    op.alter_column('actress', 'is_delete',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('actress', 'data_date',
               existing_type=sa.TIMESTAMP(timezone=26),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('actress', 'update_date',
               existing_type=sa.TIMESTAMP(timezone=26),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('posts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('posts', 'post_id',
               existing_type=sa.CHAR(length=64),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=False)
    op.alter_column('posts', 'data_time',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('posts', 'last_update',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_posts_data_time'), table_name='posts')
    op.drop_index(op.f('idx_posts_post_id'), table_name='posts')
    op.drop_index(op.f('idx_posts_source'), table_name='posts')
    op.drop_index(op.f('idx_posts_videoid'), table_name='posts')
    op.create_unique_constraint(None, 'posts', ['post_id'])
    op.alter_column('trends', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('trends', 'post_id',
               existing_type=sa.CHAR(length=64),
               type_=sqlmodel.sql.sqltypes.AutoString(length=64),
               existing_nullable=False)
    op.alter_column('trends', 'data_time',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('idx_trends_data_time'), table_name='trends')
    op.drop_index(op.f('idx_trends_post_id'), table_name='trends')
    op.alter_column('video', 'id',
               existing_type=sa.VARCHAR(length=60),
               nullable=False)
    op.alter_column('video', 'pubDate',
               existing_type=sa.TIMESTAMP(timezone=10),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('video', 'duration',
               existing_type=sa.TIMESTAMP(timezone=16),
               type_=sa.Time(),
               existing_nullable=True)
    op.alter_column('video', 'isDownloaded',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('video', 'isIgnore',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('video', 'addDate',
               existing_type=sa.TIMESTAMP(timezone=26),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('video', 'downloadDate',
               existing_type=sa.TIMESTAMP(timezone=26),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('video', 'deleteDate',
               existing_type=sa.TIMESTAMP(timezone=10),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video', 'deleteDate',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(timezone=10),
               existing_nullable=True)
    op.alter_column('video', 'downloadDate',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(timezone=26),
               existing_nullable=True)
    op.alter_column('video', 'addDate',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(timezone=26),
               existing_nullable=True)
    op.alter_column('video', 'isIgnore',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('video', 'isDownloaded',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('video', 'duration',
               existing_type=sa.Time(),
               type_=sa.TIMESTAMP(timezone=16),
               existing_nullable=True)
    op.alter_column('video', 'pubDate',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(timezone=10),
               existing_nullable=True)
    op.alter_column('video', 'id',
               existing_type=sa.VARCHAR(length=60),
               nullable=True)
    op.create_index(op.f('idx_trends_post_id'), 'trends', ['post_id'], unique=False)
    op.create_index(op.f('idx_trends_data_time'), 'trends', ['data_time'], unique=False)
    op.alter_column('trends', 'data_time',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('trends', 'post_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    op.alter_column('trends', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'posts', type_='unique')
    op.create_index(op.f('idx_posts_videoid'), 'posts', ['videoid'], unique=False)
    op.create_index(op.f('idx_posts_source'), 'posts', ['source'], unique=False)
    op.create_index(op.f('idx_posts_post_id'), 'posts', ['post_id'], unique=False)
    op.create_index(op.f('idx_posts_data_time'), 'posts', ['data_time'], unique=False)
    op.alter_column('posts', 'last_update',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('posts', 'data_time',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('posts', 'post_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    op.alter_column('posts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('actress', 'update_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(timezone=26),
               existing_nullable=True)
    op.alter_column('actress', 'data_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(timezone=26),
               existing_nullable=True)
    op.alter_column('actress', 'is_delete',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.create_table('nyaa_post_trends',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('postId', sa.INTEGER(), nullable=True),
    sa.Column('seeder', sa.INTEGER(), nullable=True),
    sa.Column('leecher', sa.INTEGER(), nullable=True),
    sa.Column('complete', sa.INTEGER(), nullable=True),
    sa.Column('data_time', sa.TIMESTAMP(timezone=26), nullable=True)
    )
    op.create_table('nyaa_post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=5), nullable=True),
    sa.Column('title', sa.VARCHAR(length=300), nullable=True),
    sa.Column('torrent_url', sa.VARCHAR(length=200), nullable=True),
    sa.Column('magnet', sa.VARCHAR(length=3000), nullable=True),
    sa.Column('size', sa.VARCHAR(length=15), nullable=True),
    sa.Column('pub_time', sa.TIMESTAMP(timezone=26), nullable=True),
    sa.Column('hash', sa.VARCHAR(length=40), nullable=True),
    sa.Column('URL', sa.VARCHAR(length=200), nullable=True),
    sa.Column('submitter', sa.VARCHAR(length=30), nullable=True),
    sa.Column('grab_time', sa.TIMESTAMP(timezone=26), nullable=True),
    sa.Column('videoid', sa.VARCHAR(length=100), nullable=True),
    sa.Column('video_quality', sa.INTEGER(), nullable=True),
    sa.Column('info', sa.VARCHAR(length=200), nullable=True)
    )
    # ### end Alembic commands ###
